{% set version = "4.0.2" %}
{%set sha256 = "739af415c7cc35d9aa4a117871b7444a0681e641124f0ddd8e79ff34a25a9386" %}

package:
  name: libconda
  version: {{ version }}

source:
  fn: libconda-{{ version }}.tar.gz
  url: https://github.com/conda/libconda/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - pycosat >=0.6.1
    - pyyaml
    - requests

test:
  imports:
    - libconda
    - libconda.progressbar

about:
  home: https://github.com/conda/libconda
  license: BSD 3-Clause
  summary: conda 4.0 based library

extra:
  recipe-maintainers:
    - jakirkham
