appveyor:
  secure: {BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: I/z3s9nCyGFANeAoU7MtXXIblc5nPtA3FfOXEq9xE/4KBztN1ZiwFdjZ91NnZIP5h7Q2+hj2DrcY+7BpGn7tbfYXE8vajqh1nCBuCt2M4ZHfnwm/pet8tgFCt5sp93lmg/m6XMWu1LHKAqCqtZ6hoyjReKcs/N0PD/dHyrVu7SH0n7GBEx/9zHkNIRc5wPcTU6DEASXA5mJXjVRWpRU3idBrUD+JSHtCP9Vv/MOMFM4fAxaBn5IQcSiIhnFbhLq/QNYcnVBKh2RpqMe58/F/aApH8XdrKf9vpzjbIZJ1AH1/11qYj8hw88Q8YTKDzrxzPTIcqe6ZYABUwT9BHyqMQunKakzTtJx2LowA2ANAf4riCi3pGKqpTO2jyRijlNJxUIaiL32nfbXXZf7RZA1mtHC5MpdwKwP2KCrP5gj/bRKkaPjlrBP5WwgLu8VT0KUrenIFc4zamilti1U2/660M082/dxUHDTd65llzZHbyR7dVIxH6u1W+wrBpc7/zV7oT+I9zxgE1N4jkh6MRvwdIGtsVI6xBPR0gYzD266aJuS6R/lizBvaPr6cL7IbrGj0v6ySt0S87u9o88ThBRB0FoTXCYeQYhjF/WQyLJHkzkaIWewXbEqwFMnals5ca0RbqbDITIpFcuTO7HQPGjowsTJGZwI/aKSdfM31NMbaObI=}
